name: Prebuild and copy dist folders

on:
    issue_comment:
        types:
            - created

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check for Specific Comment
              id: comment_check
              run: |
                  LATEST_COMMENT=$(jq -r ".comment.body" $GITHUB_EVENT_PATH)
                  if [[ "$LATEST_COMMENT" == *"/build"* ]]; then
                    echo "::set-output name=run_workflow::true"
                  else
                    echo "::set-output name=run_workflow::false"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker Compose
              run: docker-compose -f ./docker/docker-compose.prebuild.yml up -d

            - name: Copy "core/dist" from Docker container
              run: docker cp prebuild:/app/apps/core/dist ./apps/core/dist

            - name: Copy "core/dist" from Docker container
              run: docker cp prebuild:/app/apps/core/dist .

            - name: Copy "core/applications" from Docker container
              run: docker cp prebuild:/app/apps/core/applications ./apps/core/applications

            - name: Push "dist" directories to GitHub repository
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.TOKEN }}
                  files: |
                      /apps/core/dist/*
                      /apps/core/applications/*
                  branch: ${{ github.ref }}
                  force: true
                  commit_message: Update core/dist and core/applications
