name: Prebuild and copy dist folders

on:
    push:
        branches:
            - 'XSTREAM-**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image
              run: docker build . -t prebuild -f ./docker/DOCKERFILES/build/prebuild.Dockerfile

            - name: Run Docker container
              run: docker run --name prebuild prebuild

            - name: Create an artifact for dist folders
              uses: actions/upload-artifact@v2
              with:
                name: dist-artifact-${{ steps.get_commit_sha.outputs.commit_sha }}
                path: |
                    apps/core/dist
                    apps/core/applications
                retention-days: 30
                  
