name: Prebuild core & vite apps

on:
    pull_request:
        types:
            - opened
    issue_comment:
        types:
            - created
    workflow_dispatch:

jobs:
    build:
        if: github.event_name == 'workflow_dispatch' ||  github.event_name == 'pull_request' || contains(github.event.comment.body, '/build')
        runs-on: ubuntu-latest
        steps:
            - name: Show GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

            - uses: actions/github-script@v6
              if: github.event_name == 'pull_request' || contains(github.event.comment.body, '/build')
              id: get-head
              with:
                  script: |
                      const request = {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number
                      }
                      core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
                      try {
                        const result = await github.rest.pulls.get(request)
                        return result.data
                      } catch (err) {
                        core.setFailed(`Request failed with error ${err}`)
                      }

            - name: Checkout repository
              uses: actions/checkout@v3

#            - name: Build Docker image
#              run: docker build . -t prebuild -f ./docker/DOCKERFILES/build/prebuild.Dockerfile
#
#            - name: Run Docker container
#              run: docker run --name prebuild prebuild
#
#            - name: Copy apps/core/dist
#              run: docker cp prebuild:/app/apps/core/dist ./apps/core
#
#            - name: Copy apps/core/applications
#              run: docker cp prebuild:/app/apps/core/applications ./apps/core

            - name: Display outputs variable
              run: echo "The outcome is ${{ toJson(steps.get-head.outputs) }}"

            - name: Store branch variable, if workflow_dispatch get github.ref_name otherwise get head.ref if outputs.outcome is not skipped
              id: set-branch-from-ref-name
              if: github.event_name == 'workflow_dispatch'
              run: echo ::set-output name=branch::${{ github.ref_name }}

            - name: Store branch variable, if outputs.outcome is not skipped
              id: set-branch-from-head-ref
              # check if outputs.result is defined
              if: steps.get-head.outputs.result
              run: echo ::set-output name=branch::${{ fromJSON(steps.get-head.outputs.result).head.ref }}

            - name: Display branch variable
              run: echo "The branch is ${{ steps.get-branch.outputs.branch }}"

            - name: Create an artifact for core/dist and core/applications
              uses: actions/upload-artifact@v3
              with:
                  name: dist-artifact-${{ steps.get-branch.outputs.branch }}
                  path: |
                      apps/core/dist
                      apps/core/applications
                  retention-days: 30
