name: Prebuild and copy dist folders

# generate an event on create pull create, on branch name start by XSTREAM- or when a new comment is added
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - 'XSTREAM-*'
            - test
    issue_comment:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check for Specific Comment
              id: comment_check
              run: |
                  LATEST_COMMENT=$(jq -r ".comment.body" $GITHUB_EVENT_PATH)
                  if [[ "$LATEST_COMMENT" == *"/build"* ]]; then
                    echo "::set-output name=run_workflow::true"
                  else
                    echo "::set-output name=run_workflow::true"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker Compose
              run: docker-compose -f ./docker/docker-compose.prebuild.yml up --build

            - name: Copy "core/dist" from Docker container
              run: docker cp prebuild:/app/apps/core/dist ./apps/core

            - name: Copy "core/applications" from Docker container
              run: docker cp prebuild:/app/apps/core/applications ./apps/core

            - name: Commit and push 'dist' folder
              run: |
                    git config --global user.email "actions@github.com"
                    git config --global user.name "GitHub Actions"
                    git add ./apps/core/applications ./apps/core/dist -f
                    git commit -m "Push 'dist' and 'applications' folder to repository"
                    git push origin ${{ github.event.pull_request.base.ref }}
